# Generated by Django 6.0.6 on 2026-06-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('sci_fi', 'Science Fiction'), ('horror', 'Horror'), ('modern', 'Modern'), ('historical', 'Historical'), ('supernatural', 'Supernatural'), ('other', 'Other')], default='fantasy', max_length=30),
        ),
    ]
