# Generated by Django 6.0.6 on 2026-06-05 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('history', 'History'), ('culture', 'Culture'), ('magic', 'Magic'), ('technology', 'Technology'), ('politics', 'Politics'), ('religion', 'Religion'), ('species', 'Species'), ('timeline', 'Timeline'), ('geography', 'Geography'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=50)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('importance', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('essential', 'Essential')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lore_entries', to='worlds.world')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
