# Generated by Django 6.0.6 on 2026-06-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0004_loreentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='loreentry',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lore_entries', to='worlds.character'),
        ),
    ]
